# App Version Configuration
# Format: MAJOR.MINOR.PATCH
# - MAJOR: Incompatible API changes
# - MINOR: Add functionality in a backwards compatible manner
# - PATCH: Backwards compatible bug fixes
version=1.1.1
